config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :equipments do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:index, :update, :destroy] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :equipment
  belongs_to :user
  validates :date, presence: true
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  belongs_to :user
  has_many_attached :photos
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true

  include AlgoliaSearch

  algoliasearch do
    attributes :name, :description, :price
    add_attribute :extra_attr
    searchableAttributes ['name', 'description', 'extra_attr']
  end
  def extra_attr
    self.user.first_name
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :equipment
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :equipments, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  validates :email, uniqueness: true
  validates :address, presence: true
  geocoded_by :address
  after_validation :geocode
  # after_validation :geocode, if: :will_save_change_to_address?
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
    return "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?
    include Pundit

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address])
  end

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:notice] = "You are not authorized to perform this action."
    redirect_to(equipments_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @message = "None yet"
    begin
      @equipments_all = policy_scope(Equipment)
      @equipments = @equipments_all.select{|equipment|equipment.user_id == current_user.id }
    rescue ActiveRecord::RecordNotFound
      @equipments = []
    end
    @requests_wait = []
    begin
      @equipments.each do |item|
        Booking.where(equipment_id: item.id, status: "pending").each do |booking|
          @requests_wait << booking
        end
      end
    rescue ActiveRecord::RecordNotFound
      @requests_wait = []
    end

    @requests_on = []
    begin
      @equipments.each do |item|
        Booking.where(equipment_id: item.id, status: "accepted").each do |booking|
          @requests_on << booking
        end
      end
    rescue ActiveRecord::RecordNotFound
      @requests_on = []
    end

    begin
      @bookings = []
      Booking.where(user_id: current_user).each do |booking|
        @bookings << booking unless booking.status == "canceled"
      end
    rescue ActiveRecord::RecordNotFound
      @bookings = []
    end
  end

  def create
    @equipment = Equipment.find(params[:equipment_id])
    @bookings = @equipment.bookings
    @booking = Booking.new(booking_params)

    @booking.equipment = @equipment
    @booking.user = current_user
    authorize(@booking)
    unless @bookings.find{|book| book.equipment_id = params[:equipment_id] && book.user_id == current_user.id && book.status == "pending"}
      if @booking.save
        redirect_to equipment_path(@equipment)
        flash[:notice] = "Request made to #{User.find(@equipment.user_id).first_name}! Go to Dashboard to see status"
      else
        flash.now[:notice] = "Request could not be made. Please try again"
        render 'equipments/show'
      end
    else
      flash.now[:notice] = "#{@equipment.name.capitalize} already booked at this date."
      render 'equipments/show'
    end
  end

  def update
    @booking = Booking.find(params[:id])
    status = params[:format]
    booked = status.match? "accepted"
    authorize(@booking)
    @booking.update(status: status)
    @booking.equipment.update(booked: booked)
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:date)
  end
  def authorized_booking
    @equipment.bookings.find {|book|
      book.equipment_id = params[:equipment_id] &&
      book.user_id = @booking.user.id && book.status != "canceled"}
  end

end

app/controllers/equipments_controller.rb
class EquipmentsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index ]

  def index
    if params[:search]
      @equipments = Equipment.algolia_search(params[:search])
      policy_scope(Equipment)
      if @equipments.empty?
        @equipments = policy_scope(Equipment).order(:created_at)
        flash[:notice] = "Product not found"
      end
    else
      @equipments = policy_scope(Equipment).order(:created_at)
    end


    @users = User.geocoded # returns equipments with coordinates

    @markers = @users.map do |user|
      {
        lat: user.latitude,
        lng: user.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { user: user })
      }
    end
  end

  def show
    @equipment = Equipment.find(params[:id])
    @booking = Booking.new
    @bookings = @equipment.bookings
    authorize(@equipment)

    @other_equipment = Equipment.select { |equipment| equipment.id != @equipment.id }.sample
    @second_equipment = Equipment.select { |equipment| equipment.id != @equipment.id && equipment.id != @other_equipment.id }.sample
  end

  def new
    @equipment = Equipment.new
    authorize(@equipment)
  end

  def create
    @equipment = Equipment.new(equipment_params)
    @equipment.user = current_user

    authorize(@equipment)

    if @equipment.save
      redirect_to equipment_path(@equipment)
    else
      render :new
    end
  end

  def edit
    @equipment = Equipment.find(params[:id])
    authorize(@equipment)
  end

  def update
    @equipment = Equipment.find(params[:id])
    @equipment.update(equipment_params)
    authorize(@equipment)
    redirect_to equipment_path(@equipment)
  end

  def destroy
    @equipment = Equipment.find(params[:id])
    authorize(@equipment)
    @equipment.destroy
      redirect_to equipments_path
  end

  private

  def equipment_params
    params.require(:equipment).permit(:name, :description, :price, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home

  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :set_equipment
    def new
        @review = Review.new
        authorize(@review)
    end

    def create
      @review = Review.new(review_params)
      @review.user_id = current_user.id
      @review.equipment_id = @equipment.id
      
      @review.booking_id = params[:booking_id]
      authorize(@review)

      if @review.save
        redirect_to bookings_path
      else
        render :new
      end
    end

    private
    def review_params
        params.require(:review).permit(:title, :description, :rating)
    end
    def set_equipment
        @booking = Booking.find(params[:booking_id])
        @equipment = @booking.equipment
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container d-flex flex-column align-items-center">

  <div class="my-equipment my-4">

    <h2 class="border-bottom text-center my-4 py-2">MY EQUIPMENT</h2>

    <% if @equipments.empty? %>
      <p class="message-purple">-- <%= @message %> --</p>
    <% else %>
      <div class="cards d-flex flex-wrap justify-content-center">

      <% @equipments.each do |equipment| %>

          <div class="card-product m-3">
            <% if equipment.photos.first %>
              <%= cl_image_tag equipment.photos.first.key %>
            <% end %>
            <div class="card-product-infos d-flex flex-column justify-content-center align-items-betwen">
              <h4 class="text-center my-2"><strong><%= link_to equipment.name.capitalize, equipment_path(equipment.id) %></strong> <i class="fas fa-external-link-alt text-sm"></i> <% equipment.booked ? "A booking coming up" : "Free for renting" %></h4>
              <% @requests_wait.each do |request| %>
                <% if request.equipment == equipment %>
                  <div class="booking-info f-flex flex-row p-2 m-2">
                    <div class="text-center my-1"><i class="far fa-bell text-bg text-purple"></i></div>
                    <div class="d-flex flex-column">
                      <p><strong><%= request.user.first_name %></strong> asked to rent your <strong><%= request.equipment.name %></strong> </p>
                      <p><strong><i class="far fa-calendar text-purple"></i></strong> <%= request.date.strftime("%B %d, %Y") %></p>
                      <div class="group-item d-flex justify-content-center text-center">
                        <%= link_to "OK!", booking_path(request, request.status = "accepted") , method: 'patch', class: "m-1 btn btn-sm" %>
                        <%= link_to "Maybe later", booking_path(request, request.status = "declined") , method: 'patch', class: "m-1 px-2 py-1 btn btn-purple btn-sm" %>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>

          <% end %>
      </div>
    <% end %>

  </div>

  <div class="my-bookings my-4">

    <h2 class="border-bottom text-center my-4 py-2">MY BOOKINGS</h2>

    <% if @bookings.empty? %>
      <p class="message-purple">No bookings yet. Go see our equipment to start renting it!</p>
    <% else %>
      <div class="cards d-flex flex-wrap justify-content-center">
        <% @bookings.each do |booking| %>

          <div class="card-product m-3">
            <% if booking.equipment.photos %>
              <%= cl_image_tag booking.equipment.photos.first.key %>
            <% end %>
            <div class="card-product-infos d-flex flex-column justify-content-center align-items-betwen">
              <h4 class="text-center my-2"><strong><%= link_to booking.equipment.name.capitalize, equipment_path(booking.equipment.id) %></strong> <i class="fas fa-external-link-alt text-sm"></i></h4>
              <div class="booking-info f-flex flex-row p-2 m-2">
                <p><strong><i class="far fa-calendar text-purple"></i></strong> <%= booking.date.strftime("%B %d, %Y") %></p>
                <p><strong><i class="far fa-user text-purple"></i></strong> <%= User.find(booking.equipment.user_id).first_name %> <%= User.find(booking.equipment.user_id).last_name %></p>
                <p class="bigger-text"><strong>Booking status: </strong><%= booking.status %></p>
                <%= link_to "Cancel", booking_path(booking, booking.status = "canceled") , method: 'patch', class: "my-1 btn-red btn-sm", data: { confirm: "Are you sure you want to cancel the booking ?" } %><br>
                <div class="reviews mt-2 text-left d-flex">
                  <% review = booking.equipment.reviews.find{|review| review.user_id == current_user.id && review.booking_id == booking.id } %>
                  <% if review.nil? %>
                    <%= link_to "Add a review", new_booking_review_path(booking.id) %>
                  <% else %>
                    <p><strong>Your review: </strong></p>
                    <p>
                      <% (review.rating).times do |r| %>
                        <i class="fas fa-star text-primary"></i>
                      <% end %>
                      <% (5 - (review.rating)).times do |r| %>
                        <i class="far fa-star text-primary"></i>
                      <% end %>
                    </p>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>

  </div>

  <div class="rentals my-4">

    <h2 class="border-bottom text-center my-4 py-2">MY PAST RENTALS</h2>

    <% if @requests_on.empty? %>
      <p class="message-purple">No previous rentals</p>
    <% else %>
      <div class="cards d-flex flex-wrap justify-content-center">
        <% @requests_on.each do |request| %>

          <div class="card-product m-3">
            <% if request.equipment.photos %>
              <%= cl_image_tag request.equipment.photos.first.key %>
            <% end %>
            <div class="card-product-infos d-flex flex-column justify-content-center align-items-betwen m-2">
              <h4 class="text-center my-2"><strong><%= link_to request.equipment.name.capitalize, equipment_path(request.equipment.id) %></strong> <i class="fas fa-external-link-alt text-sm"></i></h4>
              <div class="booking-info f-flex flex-row p-2 m-2">
                <div class="text-center my-1"><i class="far fa-bell text-bg text-purple"></i></div>
                <p><strong><%= request.user.first_name %></strong> rented your <strong><%= request.equipment.name %></strong> </p>
                <p><strong><i class="far fa-calendar text-purple"></i></strong> <%= request.date.strftime("%B %d, %Y") %></p>
                <div class="reviews mt-2 text-left">
                  <% review = request.equipment.reviews.find{|review| review.user_id == request.user.id } %>
                  <% if review.nil? %>
                    <p>No review from <%= request.user.first_name %> yet</p>
                  <% else %>
                    <p><strong>Review received: </strong></p>
                    <p>
                      <% (review.rating).times do |r| %>
                        <i class="fas fa-star text-primary"></i>
                      <% end %>
                      <% (5 - (review.rating)).times do |r| %>
                        <i class="far fa-star text-primary"></i>
                      <% end %>
                    </p>
                  <% end %>
                </div>
                </div>
              </div>
          </div>
        <% end %>
      </div>
    <% end %>

  </div>

</div>

app/views/equipments/_carousel-card.html.erb
<div class="equip-card">
  <div class="photos">
    <div id="carousel-<%= equipment.id %>" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <% equipment.photos.each do |photo| %>
          <% if photo == equipment.photos.first %>
            <div class="carousel-item active">
          <% else %>
            <div class="carousel-item">
          <% end %>
          <%= link_to equipment_path(equipment) do %>
            <%= cl_image_tag photo.key %>
          <% end %>
          </div>
        <% end %>
      </div>
      <% if equipment.photos.attached? && equipment.photos.length > 1%>
      <a class="carousel-control-prev" href="#carousel-<%= equipment.id %>" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carousel-<%= equipment.id %>" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
      <% end %>
    </div>
  </div>
  <%= link_to equipment_path(equipment) do %>
    <div class="d-flex justify-content-between align-items-center m-3">
      <div class="equip-text d-flex flex-column">
        <span class="mb-1 text-large"><%= equipment.name.capitalize %></span>
        <span>From <strong><%= User.find(equipment.user_id).first_name %></strong></span>
      </div>
      <div class="card-right-content text-right">
        <span><%= equipment.price %> CAD</span>
        <div class="rating d-flex justify-content-end align-items-center mt-1">
          <% if !equipment.reviews.empty? %>
            <% ratings = equipment.reviews.map{|review| review.rating} %>
            <% ratings_count = equipment.reviews.count %>
            <% medium_ratings = ratings.sum.fdiv(ratings.count) %>
            <span><i class="fas fa-star text-warning"></i> <%= medium_ratings %><span class="text-muted"> (<%= ratings_count %>)</span></span>
          <% else %>
            <span class="text-muted"><i class="far fa-star text-warning"></i> (0)</span>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/equipments/show.html.erb
<div class="container-show">

  <h1 class="title my-5 text-center">
    <strong><%= @equipment.name.capitalize %></strong>

    <% if policy(@equipment).destroy? %>
      <%= link_to equipment_path(@equipment), method: :delete, data: { confirm: "Are you sure you want to delete #{@equipment.name}?" } do %>
        <i class="far fa-trash-alt smaller-icon"></i>
      <% end %>
    <% end %>


    <% if policy(@equipment).edit? %>
      <%= link_to edit_equipment_path(@equipment) do %>
        <i class="far fa-edit smaller-icon"></i>
      <% end %>
    <% end %>
  </h1>

  <div class="content-show">

    <div class="left-side white-card m-3">
      <div class="d-flex flex-grow-1 flex-column">
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <% @equipment.photos.each do |photo| %>
              <% if photo == @equipment.photos.first %>
                <div class="carousel-item active">
              <% else %>
                <div class="carousel-item">
              <% end %>
              <%= cl_image_tag photo.key, height: 400, crop: :fill, class: "d-block carousel-center image-full" %>
            </div>
            <% end %>
          </div>
          <% if @equipment.photos.attached? && @equipment.photos.length > 1%>
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
          <% end %>
        </div>
      </div>

      <div class="description p-3">
      <div class="small-info d-flex justify-content-around">
        <div class="text-center"><h3 class="border-bottom py-2 title-color"><strong>Owner</strong></h3> <p><%= User.find(@equipment.user_id).first_name %></p></div>
        <div class="text-center"><h3 class="border-bottom py-2 title-color"><strong>Price</strong></h3> <p><%= @equipment.price %>CAD /day</p></div>
      </div>
      <h3 class="border-bottom py-2 mt-5"><strong class="title-color">Description</strong></h3> <p><%= @equipment.description %></p>
      </div>

        <div class="description p-3 my-5">
          <h3 class="title-color border-bottom py-2"><strong>Reviews</strong></h3>
          <% @reviews = @equipment.reviews %>
          <% if @reviews.empty? %>
            <%= "-- None yet--"%>
          <% else %>
            <% counter = 1 %>

              <ul>
            <% @reviews.each do |review|%>
                <li class="box-white">
                  <p><strong>N°<%= counter%>:</strong> <%= review.title %>
                    <% (review.rating).times do |r| %>
                      <i class="fas fa-star text-primary"></i>
                    <% end %>
                    <% (5 - (review.rating)).times do |r| %>
                      <i class="far fa-star text-primary"></i>
                    <% end %>
                    </p>
                  <p><strong>Content:</strong> <%= review.description %></p>
                </li>
              </ul>
              <% counter += 1 %>
            <% end %>
          <% end %>
        </div>
      </div>

    <div class="right-side-show d-flex flex-column sticky-sidebar">

      <div class="orange-row p-4 my-3">
        <%= simple_form_for [@equipment, Booking.new] do |f| %>
          <%= date = f.input :date, as: :date %>
          <%= period = f.input :days %>
          <p>Total price: <span id="total-price"><%= @equipment.price %></span>CAD</p>
          <%= f.submit "Book now!", class: "btn" %>
        <% end %>
      </div>

      <div class="smaller-equipment-card-container my-3">

        <h4>Other equipments</h4>

        <%= link_to equipment_path(@other_equipment) do%>
          <div class="equip-card my-3">
            <div class="flex-grow-1 d-flex flex-column">
              <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                  <% @other_equipment.photos.each do |photo| %>
                    <% if photo == @other_equipment.photos.first %>
                      <div class="carousel-item active photos">
                    <% else %>
                      <div class="carousel-item photos">
                    <% end %>
                    <%= cl_image_tag photo.key, height: 200, crop: :fill, class: "d-block carousel-center" %>
                  </div>
                  <% end %>
                </div>
                <% if @other_equipment.photos.attached? && @other_equipment.photos.length > 1%>
                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
                </a>
                <% end %>
              </div>
            </div>
            <div class="smaller-card-info">
              <div class="smaller-equipment-title p-3 text-muted d-flex justify-content-between align-items-center">
                <h5 class="m-0"><%= @other_equipment.name.capitalize %></h5>
                <div class="rating d-flex justify-content-end align-items-center">
                  <% if !@other_equipment.reviews.empty? %>
                    <% ratings = @other_equipment.reviews.map{|review| review.rating} %>
                    <% ratings_count = @other_equipment.reviews.count %>
                    <% medium_ratings = ratings.sum.fdiv(ratings.count) %>
                    <i class="fas fa-star text-warning"></i> <%= medium_ratings %> (<%= ratings_count %>)
                  <% else %>
                    <i class="far fa-star text-warning"></i> (0)
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end%>

        <%= link_to equipment_path(@second_equipment) do%>
          <div class="equip-card my-3">
            <div class="flex-grow-1 d-flex flex-column">
              <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                  <% @second_equipment.photos.each do |photo| %>
                    <% if photo == @second_equipment.photos.first %>
                      <div class="carousel-item active photos">
                    <% else %>
                      <div class="carousel-item photos">
                    <% end %>
                    <%= cl_image_tag photo.key, height: 200, crop: :fill, class: "d-block carousel-center" %>
                  </div>
                  <% end %>
                </div>
                <% if @second_equipment.photos.attached? && @second_equipment.photos.length > 1%>
                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
                </a>
                <% end %>
              </div>
            </div>
            <div class="smaller-card-info">
              <div class="smaller-equipment-title p-3 text-muted d-flex justify-content-between align-items-center">
                <h5 class="m-0"><%= @second_equipment.name.capitalize %></h5>
                <div class="rating d-flex justify-content-end align-items-center">
                  <% if !@second_equipment.reviews.empty? %>
                    <% ratings = @second_equipment.reviews.map{|review| review.rating} %>
                    <% ratings_count = @second_equipment.reviews.count %>
                    <% medium_ratings = ratings.sum.fdiv(ratings.count) %>
                    <i class="fas fa-star text-warning"></i> <%= medium_ratings %> (<%= ratings_count %>)
                  <% else %>
                    <i class="far fa-star text-warning"></i> (0)
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end%>

      </div>

    </div>

  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    A Meal Planning Product <i class="fas fa-heart"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand navbar-lewagon">
  <div class="container">
    <div class="collapse navbar-collapse">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= cl_image_tag("riqzvy6cb5yhvbelfzxx") %>
      <% end %>
        <%= link_to "SPORTIFY", root_path, class: "nav-link white-text" %>
    </div>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "All Equipment",equipments_path , class: "nav-link white-text" %>
          </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle white-text" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.first_name %>
          </a>
          <!-- <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" /> -->
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard",bookings_path , class: "dropdown-item" %>
            <%= link_to "Add Equipment", new_equipment_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>


        <% else %>
          <li class="nav-item">
            <%= link_to "Login", "#", class: "nav-link white-text", data: { toggle: "modal", target: "#loginModal" } %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up","#", class: "nav-link white-text", data: { toggle: "modal", target: "#signupModal" } %>
          </li>

        <% end %>

      </ul>
    </div>
  </div>
</nav>

<% if !user_signed_in? %>
  <div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5>Login to the equipment!</h5>
        </div>
        <div class="modal-body">
          <%= simple_form_for(User.new, as: :user, url: session_path(:user)) do |f| %>
            <div class="form-inputs">
              <%= f.input :email,
                          required: false,
                          autofocus: true,
                          input_html: { autocomplete: "email" } %>
              <%= f.input :password,
                          required: false,
                          input_html: { autocomplete: "current-password" } %>
              <%= f.input :remember_me, as: :boolean %>
            </div>
            <div class="form-actions modal-footer">
              <%= f.button :submit, "Log in", class: "w-100" %>
            </div>
          <% end %>
          <%= link_to "Sign up","#", class: "nav-link my-1 dark-text", data: { toggle: "modal", target: "#signupModal" } %>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="signupModal" tabindex="-1" aria-labelledby="signupModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5>Create an account to see our equipment</h5>
        </div>
        <div class="modal-body">
          <%= simple_form_for(User.new, as: :user, url: registration_path(:user)) do |f| %>
            <%= f.error_notification %>
            <div class="form-inputs">
              <%= f.input :first_name,
                          required: true,
                          autofocus: true,
                          input_html: { autocomplete: "email" }%>
              <%= f.input :last_name,
                          required: true,
                          autofocus: true,
                          input_html: { autocomplete: "email" }%>
              <%= f.input :address,
                          required: true,
                          autofocus: true,
                          input_html: { autocomplete: "address" }%>
              <%= f.input :email,
                          required: true,
                          autofocus: true,
                          input_html: { autocomplete: "email" }%>
              <%= f.input :password,
                          required: true,
                          hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                          input_html: { autocomplete: "new-password" } %>
              <%= f.input :password_confirmation,
                          required: true,
                          input_html: { autocomplete: "new-password" } %>
            </div>
            <div class="form-actions modal-footer">
              <%= f.button :submit, "Sign up", class: "w-100" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>